In [3]:
import pandas as pd

<hr style="border:2px solid black"></hr>

# <center> <font color=red> Introduction to Pandas DataFrame </font> </center>

<div style="text-align: justify">
</div>

<hr style="border:2px solid black"></hr>


## <font color=blue> Section 1: Creating a DataFrames </font>

<hr style="border:1px solid black"></hr>


### Creating a DataFrame From a Dictionary </font>

---

In [10]:
example_df = pd.DataFrame({'A':[0, 1, 2, 3, 4] , 'B':['string 0','string 1','string 2', 'string 3', 'string 4']})

example_df

   A         B
0  0  string 0
1  1  string 1
2  2  string 2
3  3  string 3
4  4  string 4

---

### Creating a DataFrame From a CSV (Comma Separated Value) File </font>

---

In [17]:
celebrity_height_df = pd.read_csv('./celebrity-heights.csv')

celebrity_height_df

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.00,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.00,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M
...,...,...,...,...,...,...,...,...,...,...
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

---

### Your Turn!

Create a database from the file './baseball.csv'

---

<hr style="border:1px solid black"></hr>

## <font color=blue> Section 2: DataFrame Summaries</font>

+ [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html#): Column data types.
+ [describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html#): Summary statistics for numerical columns
+ [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html), [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail) : Show first or last few rows of a table

<hr style="border:1px solid black"></hr>

### <font color=black> info() </font>

<div style="text-align: justify">
To display information about the columns and datatypes, use <b>info()</b>.
</div>

---

In [14]:
example_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      object
dtypes: int64(1), object(1)
memory usage: 132.0+ bytes

In [16]:
celebrity_height_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         5502 non-null   int64
 1   firstname  5502 non-null   object
 2   midname    340 non-null    object
 3   lastname   5416 non-null   object
 4   fullname   5502 non-null   object
 5   ftin       5502 non-null   object
 6   feet       5502 non-null   int64
 7   inches     5502 non-null   float64
 8   meters     5502 non-null   float64
 9   gender     4988 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 301.0+ KB

---

### <font color=black> describe() </font>

<div style="text-align: justify">
To get a summary and statistics of any numerical columns, use <b>describe()</b>.
</div>

---

In [23]:
example_df.describe()

              A
count  5.000000
mean   2.000000
std    1.581139
min    0.000000
25%    1.000000
50%    2.000000
75%    3.000000
max    4.000000

In [19]:
celebrity_height_df.describe()

                id         feet       inches       meters
count  5502.000000  5502.000000  5502.000000  5502.000000
mean   2751.500000     5.244638     5.702225     1.743402
std    1588.434922     0.462110     3.414453     0.111375
min       1.000000     2.000000     0.000000     0.812800
25%    1376.250000     5.000000     3.000000     1.663700
50%    2751.500000     5.000000     6.000000     1.739900
75%    4126.750000     5.000000     8.500000     1.822450
max    5502.000000     8.000000    11.750000     2.717800

---

### <font color=black> head() </font>

<div style="text-align: justify">
To display only the first n rows of the DataFrame, use <b>head(n)</b>.
</div>

---

In [21]:
example_df.head(3)

   A         B
0  0  string 0
1  1  string 1
2  2  string 2

In [5]:
celebrity_height_df.head(15)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.06680,M
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.0,1.06680,M
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.0,1.09220,M
7,6,Kenny,NaN,Baker,Kenny Baker,3ft 8in,3,8.0,1.11760,M
8,7,Billy,NaN,Barty,Billy Barty,3ft 9in,3,9.0,1.14300,M
9,10,Kiran,NaN,Shah,Kiran Shah,4ft 1.7in,4,1.7,1.26238,F
10,17,Nikki,NaN,Blonsky,Nikki Blonsky,4ft 10in,4,10.0,1.47320,F
11,18,Kristin,NaN,Chenoweth,Kristin Chenoweth,4ft 10in,4,10.0,1.47320,F
12,19,Danny,NaN,DeVito,Danny DeVito,4ft 10in,4,10.0,1.47320,M
13,20,Kelly,NaN,Stables,Kelly Stables,4ft 10in,4,10.0,1.47320,F
14,32,Jeillo,NaN,Edwards,Jeillo Edwards,4ft 11.5in,4,11.5,1.51130,NaN

---

### <font color=black> Displaying the Last Rows </font>

<div style="text-align: justify">
To display only the last n rows of the DataFrame, use <b>tail(n)</b>.
</div>

---

In [11]:
example_df.tail(2)

   A         B
3  3  string 3
4  4  string 4

In [6]:
celebrity_height_df.tail(15)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5487,5488,Carel,NaN,Struycken,Carel Struycken,7ft 0in,7,0.000,2.133600,NaN
5488,5493,Wilt,NaN,Chamberlain,Wilt Chamberlain,7ft 1.06in,7,1.060,2.160524,NaN
5489,5494,Richard,NaN,Kiel,Richard Kiel,7ft 1.5in,7,1.500,2.171700,M
5490,5495,Kareem,Abdul,Jabbar,Kareem Abdul Jabbar,7ft 1.625in,7,1.625,2.174875,M
5491,5489,Shaquille,NaN,O'Neal,Shaquille O'Neal,7ft 1in,7,1.000,2.159000,M
5492,5490,Dalip,NaN,Singh,Dalip Singh,7ft 1in,7,1.000,2.159000,NaN
5493,5491,Football,NaN,Soccer,Football Soccer,7ft 1in,7,1.000,2.159000,NaN
5494,5492,Ian,NaN,Whyte,Ian Whyte,7ft 1in,7,1.000,2.159000,M
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.000,2.184400,M
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.000,2.260600,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.500,2.298700,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.000,2.286000,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.250,2.317750,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.750,2.355850,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.000,2.717800,M

---

### Your Turn!

Use info(), describe(), head(), and tail() to get info about './baseball.csv'

---

<hr style="border:1px solid black"></hr>


## <font color=blue> Selecting Data</font>

<hr style="border:1px solid black"></hr>

### `[]` Bracket selection

Syntax: `X[selector]`
+ To select columns the `selector` can be
    + A column label (string)
    + A list of column labels (list of strings)
+ To select rows the `selector` can be
    + A slice
    + A boolean mask

### Select a single column (string)

---

In [14]:
celebrity_height_df[['firstname']]

     firstname
0        Verne
1        Herve
2        David
3         Tony
4      Warwick
...        ...
5497   General
5498   Matthew
5499     Sandy
5500       Sun
5501    Robert

[5502 rows x 1 columns]

---

### Select multiple columns (list of strings)

---

In [13]:
celebrity_height_df[['firstname','lastname']]

     firstname     lastname
0        Verne       Troyer
1        Herve  Villechaize
2        David    Rappaport
3         Tony          Cox
4      Warwick        Davis
...        ...          ...
5497   General       Height
5498   Matthew      McGrory
5499     Sandy        Allen
5500       Sun         Ming
5501    Robert       Wadlow

[5502 rows x 2 columns]

---

### Select rows with slice indexing
[Slice indexing](https://docs.python.org/3/tutorial/introduction.html), in which you specify a start index, a stop index, and a step, works in the same way in Pandas as it does for regaular Python lists.

---

In [15]:
celebrity_height_df[3:5]

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.0668,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.0668,M

---

### Select rows with a boolean mask

You can use a boolean list or a boolean Series as a mask for filtering rows.

---

In [16]:
celebrity_height_df[celebrity_height_df['meters']>2.2]

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

---

### Your Turn!

Use a boolean mask to find the players who make less than 400,0000 from './baseball.csv'

---